version: '3.8'

services:
  # Streamlitアプリケーション（メインサービス）
  app-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: app-dashboard:latest
    container_name: app-dashboard
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - AUTH_DEBUG_MODE=true
      - TZ=Asia/Tokyo
    volumes:
      # 開発用：必要なファイルをマウント
      - ./src/auth:/app/src/auth
      - ./src/components:/app/src/components
      - ./src/utils:/app/src/utils
      - ./src/analysis:/app/src/analysis
      - ./app.py:/app/app.py
      # データディレクトリのマウント追加
      - ./corporate_bias_datasets:/app/corporate_bias_datasets
    restart: unless-stopped
    # 簡素化されたヘルスチェック
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 60s
      timeout: 30s
      retries: 2
      start_period: 60s

  # データ分析パイプライン（オプションサービス）
  data-pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: corporate-bias-pipeline
    environment:
      - PYTHONPATH=/app
    volumes:
      # データディレクトリをマウント
      - ./corporate_bias_datasets:/app/corporate_bias_datasets
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: "no"
    # データ収集完了後にコンテナを停止
    command: ["python", "-m", "scripts.run_bias_analysis"]
    profiles:
      - pipeline  # 必要時のみ起動