version: '3.8'

services:
  data-pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: corporate-bias-pipeline
    environment:
      - PYTHONPATH=/app
    volumes:
      # データディレクトリをマウント
      - ./corporate_bias_datasets:/app/corporate_bias_datasets
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: "no"
    # データ収集完了後にコンテナを停止
    command: ["python", "-m", "scripts.run_bias_analysis"]