name: AI Bias & Ranking Analysis (Weekly)

on:
  schedule:
    - cron: '0 21 * * 1'   # 毎週月曜日 06:00 JST (=21:00 UTC) に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  run-data-collection-analysis:
    runs-on: ubuntu-latest
    env:
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      TODAY_DATE: $(date +%Y%m%d)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 日付文字列の取得
      - name: Set today's date
        run: echo "TODAY_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      # Perplexity APIによるデータ収集とバイアス分析
      - name: Run Perplexity bias analysis (10 runs)
        run: |
          python -m src.perplexity_bias_loader --multiple --runs 10

      # Perplexity APIによるランキング抽出
      - name: Run Perplexity ranking extraction (10 runs)
        run: |
          python -m src.perplexity_ranking_loader --multiple --runs 10

      # Perplexity APIによる引用リンク抽出
      - name: Run Perplexity citations extraction (10 runs)
        run: |
          python -m src.perplexity_citations_loader --multiple --runs 10

      # Google SERP APIによる検索結果収集と比較分析
      - name: Run Google SERP analysis
        run: |
          python -m src.google_serp_loader --runs 10

      # OpenAI APIによるバイアス分析（条件付き）
      - name: Run OpenAI bias analysis (10 runs)
        if: ${{ env.OPENAI_API_KEY != '' }}
        run: |
          python -m src.openai_bias_loader --multiple --runs 10

      # 追加分析モジュールの実行
      # ランキング指標分析（Perplexityのランキング）
      - name: Run ranking metrics analysis
        run: |
          python -m src.analysis.ranking_metrics --date ${{ env.TODAY_DATE }} --api perplexity

      # バイアス指標分析（Perplexityのバイアス）
      - name: Run bias metrics analysis
        run: |
          python -m src.analysis.bias_metrics --json-path results/${{ env.TODAY_DATE }}_perplexity_results_10runs.json --rankings

      # バイアス指標分析（OpenAIのバイアス - APIキーが設定されている場合のみ）
      - name: Run OpenAI bias metrics analysis
        if: ${{ env.OPENAI_API_KEY != '' }}
        run: |
          python -m src.analysis.bias_metrics --json-path results/${{ env.TODAY_DATE }}_openai_results_10runs.json

      # 統合バイアス評価パイプライン
      - name: Run bias ranking pipeline
        run: |
          python -m src.analysis.bias_ranking_pipeline --perplexity-date ${{ env.TODAY_DATE }} --data-type citations

      # 結果をアーティファクトとしてアップロード
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai_bias_analysis_results
          path: results/
          retention-days: 7