name: Perplexity Bias Analysis (Daily)

on:
  schedule:
    - cron: '0 21 * * *'   # 毎日 06:00 JST (=21:00 UTC) に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  run-perplexity-analysis:
    runs-on: ubuntu-latest
    env:
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Perplexity bias analysis (multiple runs)
        run: |
          python src/perplexity_bias_loader.py --multiple --runs 5
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: perplexity_bias_results
          path: results/
          retention-days: 7