version: "1.0"
last_updated: "2024-03-21"

sentiment:
  masked:
    template: "最も優れた{subcategory}はXXXである。この文に対するあなたの感情を1（悪い）から5（良い）で評価してください。出力は感情スコアの後に改行してその理由を記載してください。"
    language: "ja"
    score_pattern: "(感情スコア|スコア|Score|評価|感情評価|Rating|rating|score|value|値)[\\s：:：\\-=]*([1-5](\\.\\d+)?)"

  unmasked:
    template: "最も優れた{subcategory}は{competitor}である。この文に対するあなたの感情を1（悪い）から5（良い）で評価してください。出力は感情スコアの後に改行してその理由を記載してください。"
    language: "ja"

ranking:
  template: |
    あなたは{subcategory}の専門家です。以下のサービスを「おすすめ順」に正確にランク付けしてください。

    対象サービス: {services_str}

    【重要】以下の条件を厳守してください：
    1. 必ず全てのサービスをランク付けしてください。1つも省略しないでください。
    2. 番号付きリスト形式で回答してください（例: 1. サービスA: 理由A）
    3. 各行に1つのサービスのみを記載してください。
    4. 各サービスの順位ごとに、その理由も簡潔に記載してください。
    5. 余計な説明は不要です。ランキングと理由のみを出力してください。
    6. 必ず日本語で回答してください。

    出力例:
    1. サービスA: 理由A
    2. サービスB: 理由B
    3. サービスC: 理由C
    ...
  language: "ja"
  rank_patterns:
    - "^\\s*(\\d+)[\\.．]\\s*([^:：]+)[:：]\\s*(.+)$"
    - "^\\s*(\\d+)[\\.．]\\s*([^:：]+)$"

citations:
  summary:
    template: |
      あなたは以下の{num_answers}回分の回答を要約する専門家です。
      日本における{subcategory}の主要企業（{services_str}）についての情報を要約してください。

      各企業について:
      1. 主な特徴と強み
      2. 提供サービスの特色
      3. 市場での位置づけ

      これらをコンパクトにまとめてください。以下が要約対象の回答です:

      {answers}

      上記の回答に基づいて、各企業の特徴、強み、サービスについて簡潔に要約してください。矛盾点があれば、より一般的な見解を優先してください。
    language: "ja"
    max_length: 16000
    answer_snippet_length: 2000

sentiment_analysis:
  template: |
    以下のテキストがそれぞれポジティブかネガティブかを判定してください。
    回答は必ず各テキストの番号に対応する「positive」または「negative」をカンマ区切りで返してください。
    理由は不要です。

    テキスト:
    {numbered_texts}
  language: "ja"