version: "1.0"
last_updated: "2024-03-21"

sentiment:
  masked:
    template: "{subcategory}それ自体について、10点満点で評価してください。冒頭に点数のみを記載し、その後理由を説明してください。必ず日本語で回答してください。"
    language: "ja"
    score_pattern: "(感情スコア|スコア|Score|評価|感情評価|Rating|rating|score|value|値|点数|点)[\\s：:：\\-=]*([1-9]|10)(\\.\\d+)?"

  unmasked:
    template: |
      {subcategory}において、{competitor}を10点満点で評価してください。冒頭に点数のみを記載し、その後理由を説明してください。
      回答は「N点」または「**N点**」の形式で、Nは1〜10の整数または小数点1桁までとしてください。
      出力はスコアの後に改行してその理由を記載してください。
    language: "ja"

ranking:
  template: |
    あなたは{subcategory}の専門家です。以下のサービスを「おすすめ順」に正確にランク付けしてください。

    対象サービス: {services_str}

    【重要】以下の出力形式を厳密に守ってください：
    1. 必ず全てのサービスをランク付けしてください（1つも省略禁止）
    2. 必ず以下の厳密なフォーマットで出力してください：
       「順位. サービス名: 理由」
    3. サービス名は上記リストに含まれる名前を正確に使用してください
    4. マークダウン記法（**太字**、#見出し、*斜体*等）は一切使用しないでください
    5. 各行に1つのサービスのみを記載してください
    6. 余計な前置きや説明文は不要です。ランキングのみを出力してください
    7. 注意書きやコメントは不要です
    8. リストにないサービス名は絶対に含めないでください

    正しい出力例：
    1. AWS: 最大の市場シェアと豊富なサービスカタログ
    2. Azure: エンタープライズ向けの強固な統合機能
    3. Google Cloud: 機械学習とデータ分析に優秀
    4. Oracle Cloud: データベース技術に強み
    5. IBM Cloud: AIとハイブリッドクラウドに特化

    上記の形式を厳守してください。
  language: "ja"
  rank_patterns:
    # 基本パターン（推奨形式）
    - "^\\s*(\\d+)[\\.．)]\\s*([^:：\\-*#]+?)\\s*[:：]\\s*(.+)$"
    # マークダウン太字パターン（フォールバック）
    - "^\\s*(\\d+)[\\.．)]?\\s*\\*\\*([^*]+?)\\*\\*\\s*[:：\\-]?\\s*(.*)$"
    # 見出し記法パターン（フォールバック）
    - "^\\s*(\\d+)[\\.．)]?\\s*#+\\s*([^#:：\\-]+?)\\s*[:：\\-]?\\s*(.*)$"
    # 理由なしパターン
    - "^\\s*(\\d+)[\\.．)]\\s*([^:：\\-*#]+?)\\s*$"
    # より柔軟な区切り文字パターン
    - "^\\s*(\\d+)[\\.．)]?\\s*(.+?)\\s*[\\-：:→]\\s*(.+)$"
    # ハイフンや矢印区切りパターン
    - "^\\s*(\\d+)[\\.．)]?\\s*([^\\-→]+?)\\s*[\\-→]\\s*(.+)$"

citations:
  summary:
    template: |
      あなたは以下の{num_answers}回分の回答を要約する専門家です。
      日本における{subcategory}の主要企業（{services_str}）についての情報を要約してください。

      各企業について:
      1. 主な特徴と強み
      2. 提供サービスの特色
      3. 市場での位置づけ

      これらをコンパクトにまとめてください。以下が要約対象の回答です:

      {answers}

      上記の回答に基づいて、各企業の特徴、強み、サービスについて簡潔に要約してください。矛盾点があれば、より一般的な見解を優先してください。
    language: "ja"
    max_length: 16000
    answer_snippet_length: 2000

sentiment_analysis:
  template: |
    以下のテキストがそれぞれポジティブかネガティブかを判定してください。
    回答は必ず各テキストの番号に対応する「positive」または「negative」をカンマ区切りで返してください。
    理由は不要です。

    テキスト:
    {numbered_texts}
  language: "ja"